(function() {var implementors = {};
implementors["hvif_rs"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='enum' href='hvif_rs/types/path/enum.HVIFPointCommand.html' title='hvif_rs::types::path::HVIFPointCommand'>HVIFPointCommand</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='struct' href='hvif_rs/types/path/struct.HVIFPoint.html' title='hvif_rs::types::path::HVIFPoint'>HVIFPoint</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='struct' href='hvif_rs/types/shape/struct.HVIFf24.html' title='hvif_rs::types::shape::HVIFf24'>HVIFf24</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='struct' href='hvif_rs/types/shape/struct.HVIFMatrix.html' title='hvif_rs::types::shape::HVIFMatrix'>HVIFMatrix</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='enum' href='hvif_rs/types/shape/enum.HVIFTransformer.html' title='hvif_rs::types::shape::HVIFTransformer'>HVIFTransformer</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='enum' href='hvif_rs/types/style/enum.HVIFGradientType.html' title='hvif_rs::types::style::HVIFGradientType'>HVIFGradientType</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='struct' href='hvif_rs/types/style/struct.HVIFGradientColor.html' title='hvif_rs::types::style::HVIFGradientColor'>HVIFGradientColor</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='struct' href='hvif_rs/types/struct.HVIFFlag.html' title='hvif_rs::types::HVIFFlag'>HVIFFlag</a>",];
implementors["nom"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='enum' href='nom/enum.Needed.html' title='nom::Needed'>Needed</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='enum' href='nom/enum.Move.html' title='nom::Move'>Move</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/marker/trait.Copy.html' title='core::marker::Copy'>Copy</a> for <a class='enum' href='nom/enum.FileProducerState.html' title='nom::FileProducerState'>FileProducerState</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
